### ISSUE TITLE
parsing during interpretation

### ISSUE THREAD

**Issue by cscherrer** [riadas/Autumn.jl#17]
`interpret.jl` has a function
```julia
function start(aex::AExpr, rng=Random.GLOBAL_RNG; show_rules=-1)
```
that includes this line:
```julia
_, env = interpret(AExpr(:assign, Symbol(string(:prev, uppercasefirst(string(var_name)))), parseautumn("""(fn () (get (.. (.. state histories) $(string(var_name))) (- (.. state time) 1) $(var_name)))""")), env) 
```

So it looks like we're starting with an AExpr, using it to build a string, and then re-parsing. Can we restructure this to avoid strings? Ideally we'd parse once and then work entirely in terms of the internal representation (or anything more strongly typed).

**Comment by riadas** [comment]
Closed by #22
