### ISSUE TITLE
Remove bad tests

### ISSUE THREAD

**Issue by zenna** [riadas/Autumn.jl#4]
Currently, tests are failing due to some of them being out of date.

Remove these.

**Comment by riadas** [comment]
Removed the outdated tests, but tests are still failing due to `Test.typesubtract` on Julia 1.6 (?): https://github.com/JuliaData/CSV.jl/issues/744

**Comment by zenna** [comment]
See https://github.com/zenna/Omega.jl/blob/lang/OmegaTest/src/testutil.jl
